### ISSUE TITLE
Implement a burger menu to open options/navigation

### ISSUE THREAD

**Issue by ben-me** [ben-me/capstone-project#15]
**Value Proposition
As a user I need to have a menu to be able to quickly navigate between functions.

**Description**
![Image](https://user-images.githubusercontent.com/109357901/192297075-59f6c6ec-d081-4edc-ba75-81d19c0973d9.png)

**Acceptance Criteria**
- [x] I can see a burger menu on all pages
- [x] when clicking on the burger menu, an overlay opens
- [x] the overlay displays text, which link me to the different pages when being clicked on

**Tasks**
- [x] create svg/image on all relevant pages
- [x] make svg/image clickable and link to a component
- [x] create component for overlay
- [x] make texts in component link to different pages
