### ISSUE TITLE
Moving data to a database

### ISSUE THREAD

**Issue by ben-me** [ben-me/capstone-project#17]
**Value Proposition**
As a user I need to be able to store my settings and reservations online to be able to acess them from anywhere.

**Description**
The data will be moved from the local js file to a mongoDB Database.

**Acceptance Criteria**
- [x] newly added data is still stored after exiting the app
- [x] the data is still there when the app is opened again

**Tasks**

- [x] create mongoDB
- [x] move data from js file to mongoDB
- [x] connect app to database
- [x] render data in app
