### ISSUE TITLE
Implementing a User login

### ISSUE THREAD

**Issue by ben-me** [ben-me/capstone-project#18]
**Value Proposition**
As a user I need a login to be able to store my personalized data and settings on the database

**Description**

![Image](https://user-images.githubusercontent.com/109357901/192543940-69ec4a77-08c8-4f74-8cc5-ed7429c4e196.png)

![Image](https://user-images.githubusercontent.com/109357901/192565234-51691301-adde-41bf-9e83-73eba3d3002d.png)

**Acceptance criteria**
- [ ] when opening the app I am presented with a login field
- [ ] there are 2 inputs that allow me to put in a username and a password
- [ ] entering the correct data and clicking "Sign in" will proceed me to the next page
- [ ] entering the wrong data will give me an error
- [ ] there is a button "sign up" that allows me to create a user

**Tasks**

- [ ] create a section for the login elements
- [ ] create two seperate input field for username and password
- [ ] create a button for sign in that compares the input values with database users
- [ ] create a button for sign up that switches the section to  "register" input fields
- [ ] create a button on the sign up part that says "register" and saves the inputs to the database
- [ ] create a button to cancel the sign up process

**Comment by deki84** [comment]
Good work . Looks very good
