### ISSUE TITLE
Display a list of available rooms

### ISSUE THREAD

**Issue by ben-me** [ben-me/capstone-project#2]
**Value Proposition**
As an employee in a company with shared desks/co-working, I need to see a list of all rooms to be able to receive information about my workday.

**Description**
| Frame 1  | Frame 2  |
--------------------------------------------------|------------------------------------------------
| ![grafik](https://user-images.githubusercontent.com/109357901/190159501-75c2f7d4-9a9e-4909-ab41-0c57743e487f.png) | ![grafik](https://user-images.githubusercontent.com/109357901/190167615-b701cdfb-8e45-4c1c-992c-1105230a38ae.png) |

**Acceptance Criteria**
- [x] when clicking the button to show all the rooms a list should be displayed
- [x] when clicking on the arrow in frame 2 the first screen should appear again
- [x] pressing anywhere except the button in frame 1 will not advance to frame 2

**Tasks**
- [x] create a branch
- [x] create a page with a button that has the label "Show me all rooms"
- [x] create a second page with a &lt;h1> "All Rooms"
- [x] create an unordered list on the second page to contain all the rooms as list elements
- [x] write logic to render the rooms (useState array)

**Comment by MerleMak** [comment]
Hi Benedikt, 
Nice first User Story, I have some comments:
- In your Value Proposition you could maybe find a better description of your user (just for the first user story, so it's visible at first sight who will be your target group (e.g. "As a customer of a co-working Space,..)
- Also you didn't plan on putting a reservation function into you app just yet, so maybe you can find a more general description why your user needs this list of rooms( e.g. ".. I need to access a list of all rooms available, to be able to receive information for my workday") 
Other than that great job!
- Your wireframe is in English and in German, it is better to be coherent in your language choice

**Comment by ben-me** [comment]
Updated the value proposition text to include more information about the target audience. Also swapped out the frame 2 of my wireframe to be completely in english.

**Comment by MerleMak** [comment]
good job :)
