### ISSUE TITLE
Select a room and see the desks it contains

### ISSUE THREAD

**Issue by ben-me** [ben-me/capstone-project#3]
**Value Proposition**
As a user I need to click on the rooms to see the available desks/spaces to be able to get more information about preexisting reserverations for my selected desk.

**Description**
![grafik](https://user-images.githubusercontent.com/109357901/190415592-372332d8-7f2d-411a-b031-32b5a75a451c.png)

**Acceptance Criteria**
- [x] I am able to select one of the rooms that appears in the list
- [x] selecting a room brings me to the overview of all desks/spaces in that room

**Tasks**
- [x] create a new branch
- [x] make rooms contain information about available desks/spaces (object-array)
- [x] add click functionality for each room in the list so you can jump to the newly created page
- [x] create a new page where the header is the name of the selected room
- [x] create container on the new page where all the desks can be rendered
- [x] write logic to render desks
