### ISSUE TITLE
Select a desk to see information about existing reservations

### ISSUE THREAD

**Issue by ben-me** [ben-me/capstone-project#4]
**Value Proposition**
As a user I need to click on one of the desks to be able get information about the desks availability.

**Description**
![grafik](https://user-images.githubusercontent.com/109357901/190178810-42af5e47-f914-42f6-a38d-a807430584ee.png)

**Acceptance Criteria**
- [x] i can click on a single desk/space in a room to see its details
- [x] the clicked desk/space gets highlighted
- [x] the selected desk/space opens a small window where details about existing reservations are displayed
- [x] pressing the red cross icon closes the details and removes the highlighting of the desk
- [x] pressing on another desk while details for one are open switches the highlighting and information to the data of the newly selected one

**Tasks**
- [x] create new branch
- [x] button should toggle a box with information when being clicked on
- [x] button should be highlighted in a differnt color while the details are being shown
- [x] add red cross button inside details to close
- [x] pressing another button(desk) should display its details instead of the old one
