### ISSUE TITLE
Reserving a selected desk for a specified time

### ISSUE THREAD

**Issue by ben-me** [ben-me/capstone-project#5]
**Value Proposition**
As a user I need to reserve one of the desks to be able to make sure that I can work there on the specified date and time.

**Description**
![grafik](https://user-images.githubusercontent.com/109357901/190635723-3bf93ff7-5743-44d4-a0da-beb24e82a1ef.png)

**Acceptance Criteria**
- [x] I can click "reserve desk" when a desk is highlighted/selected
- [x] I can enter a date, a start time and an end time for my reservation
- [x] there is a checkbox to make my reservation private
- [ ] ~~entering a date in the past results in an error when saving~~  (Don't need to change the date)
- [x] setting the end time to be before the start time results in an error when saving
- [x] reserving a time that is already reserved results in an error

**Tasks**
- [x] create a new branch
- [x] create a button for reservations
- [x] make a toast pop up where information can be entered
- [x] check the fields for invalid entries on save
- [x] make two buttons: one to cancel the reservation (close the toast without saving) and one to reserve (close toast and saving)

**Comment by K-Juno** [comment]
Hey ya, I only have typo corrections:

> As a user I need to reserve one of the **_desks_**

>  I can click "reserve desk" when a desk is **_highlighted_**

> make two buttons: one to **_cancel_** the reservation

Other than that, happy coding!

**Comment by ben-me** [comment]
Thanks for the review and feedback.
Fixed the mistakes :)
