### ISSUE TITLE
Adding display for date in room and option to change date

### ISSUE THREAD

**Issue by ben-me** [ben-me/capstone-project#6]
**Value Proposition**
As a user I need to see and change the date to be able to reserve in the future and see possible reservations of the future.

**Description**
![grafik](https://user-images.githubusercontent.com/109357901/190648550-5888853f-216a-428e-b3f5-6b6902690af8.png)
![grafik](https://user-images.githubusercontent.com/109357901/190658247-abfc62cc-8d8f-45a9-99c3-c47b2939c3f4.png)

**Acceptance Criteria**
- [x] when switching into a room today's date should be displayed above the desks
- [x] clicking on the date opens a calendar where I can change the date
- [x] clicking on a date in the calendar closes the calendar and changes the shown date
- [x] the displayed date above the desks is, by default, the recommended date when trying to make a reservation

**Tasks**
- [x] create a container for the date
- [x] render the current date inside the container
- [x] make the date have an onclick to open a toast window with a full calender and and display the current month
- [x] make the dates have an onclick that closes the toast window and changes the shown date to the newly selected one

**Comment by MerleMak** [comment]
Hi Benedikt, 
Nice job for this user story,
please rephrase the last point of you AC, as I am not sure that I understood correctly.
Did you already have a look which library you could use for the calendar? There are some nice ones, this could be worth checking out before and already including the steps into your user story :)

**Comment by ben-me** [comment]
Thanks for the review :)
Rephrased the sentence. Is it clearer now?
I haven't checked out any library yet. Should I do this as user story or include in this one or in the "spike" Thomas mentioned?
